# Generated by Django 4.1.7 on 2023-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_remove_school_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
